# Generated by Django 4.0.2 on 2022-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('restriction_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('region_id', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('hospitalised', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('died', models.IntegerField()),
                ('vaccinated_first_component_cumulative', models.IntegerField()),
                ('vaccinated_fully_cumulative', models.IntegerField()),
                ('collective_immunity', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
