# Generated by Django 4.0.2 on 2022-02-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalstats',
            name='region_id',
        ),
        migrations.AddField(
            model_name='regionalstats',
            name='region',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stats.regions'),
        ),
        migrations.AlterField(
            model_name='regionalrestrictions',
            name='region',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stats.regions'),
        ),
        migrations.AlterField(
            model_name='regionalrestrictions',
            name='restriction_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stats.restrictions'),
        ),
    ]
