# Generated by Django 4.0.2 on 2022-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_regionalstats_region_id_regionalstats_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalrestrictions',
            old_name='restriction_id',
            new_name='restriction',
        ),
    ]
