# Generated by Django 4.0.2 on 2022-02-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rename_restriction_id_regionalrestrictions_restriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastParsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_datetime', models.DateTimeField(auto_now=True)),
                ('parsed_info_datetime', models.DateTimeField()),
            ],
        ),
    ]
