# Generated by Django 4.0.2 on 2022-02-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_lastparsed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastparsed',
            name='parse_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последней проверки'),
        ),
        migrations.AlterField(
            model_name='lastparsed',
            name='parsed_info_datetime',
            field=models.DateTimeField(verbose_name='Время последних взятых данных'),
        ),
        migrations.AlterField(
            model_name='regionalrestrictions',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='regionalrestrictions',
            name='region',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stats.regions', verbose_name='id региона'),
        ),
        migrations.AlterField(
            model_name='regionalrestrictions',
            name='restriction',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stats.restrictions', verbose_name='Ограничение'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='collective_immunity',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Коллективный иммунитет'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='died',
            field=models.IntegerField(verbose_name='Умерло'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='hospitalised',
            field=models.IntegerField(verbose_name='Госпитализировано'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='new_cases',
            field=models.IntegerField(verbose_name='Новые случаи'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='recovered',
            field=models.IntegerField(verbose_name='Вылечились'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='region',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stats.regions', verbose_name='id региона'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='vaccinated_first_component_cumulative',
            field=models.IntegerField(verbose_name='Вакцинировано первым компонентом'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='vaccinated_fully_cumulative',
            field=models.IntegerField(verbose_name='Вакцинировано полностью'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
    ]
