# Generated by Django 4.0.2 on 2022-02-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_lastparsed_parse_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastparsed',
            options={'verbose_name': 'Последний парсинг', 'verbose_name_plural': 'Последний парсинг'},
        ),
    ]
