# Generated by Django 4.0.2 on 2022-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_lastparsed_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalstats',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
