# Generated by Django 4.0.2 on 2022-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_regionalstats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastparsed',
            name='parse_success',
            field=models.BooleanField(default=False, verbose_name='Парсинг прошел успешно'),
        ),
    ]
