# Generated by Django 4.0.2 on 2022-03-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_lastparsed_parse_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastparsed',
            name='parsed_info_datetime',
            field=models.DateField(verbose_name='Время последних взятых данных'),
        ),
    ]
