# Generated by Django 4.0.2 on 2022-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_lastparsed_parsed_info_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalstats',
            name='vaccinated_first_component_cumulative',
            field=models.IntegerField(verbose_name='Вакцинировано 1 комп.'),
        ),
        migrations.AlterField(
            model_name='regionalstats',
            name='vaccinated_fully_cumulative',
            field=models.IntegerField(verbose_name='Вакцинировано 2 комп.'),
        ),
    ]
