# Generated by Django 4.0.2 on 2022-04-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_alter_regionalstats_vaccinated_first_component_cumulative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
