# Generated by Django 4.0.2 on 2022-04-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_restrictions_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionalrestrictions',
            unique_together={('date', 'region', 'restriction')},
        ),
    ]
